// scripts/import-sets.ts
//
// BUILD-TIME ONLY. Run manually by Red.
//
//   pnpm import:sets
//
// Pulls the full TCG set list from YGOPRODeck's cardsets endpoint and joins it
// with the card database (which records each card's set codes) to produce, for
// every set: code, name, TCG release date, card count, and the passcodes
// printed in it. Writes:
//
//   assets/sets/db.json
//   assets/sets/index.json   (lightweight manifest)
//
// Requires `pnpm import:cards` to have run first (so set → card mapping can be
// resolved from db.json's per-card `sets`). TCG ONLY.
//
// Set logos/box art are downloaded separately by build-image-pack.ts into
// assets/sets/images/{CODE}.jpg.

import { join } from "node:path";
import { PATHS, YGO, fetchJson, fetchSetReleaseDate, writeJson, readJson } from "./_lib.ts";

interface CardLite {
  id: number;
  sets: { code: string; name: string }[];
}
interface UpstreamSet {
  set_name: string;
  set_code: string;
  num_of_cards?: number;
  tcg_date?: string;
}

/** Set-code prefix from a full print code, e.g. "LOB-EN001" → "LOB". */
const prefixOf = (code: string): string => code.split("-")[0]!;

async function main() {
  const db = await readJson<{ cards: CardLite[] }>(PATHS.cardsDb);
  if (!db || !Array.isArray(db.cards)) {
    console.error("✗ assets/cards/db.json not found. Run `pnpm import:cards` first.");
    process.exit(1);
  }

  // Reverse index: set-code prefix → passcodes, plus the set name seen on the
  // card's prints (used as a fallback name for sets upstream doesn't list).
  const cardsBySet = new Map<string, number[]>();
  const nameBySet = new Map<string, string>();
  for (const c of db.cards) {
    for (const p of c.sets ?? []) {
      const code = prefixOf(p.code);
      const arr = cardsBySet.get(code) ?? [];
      arr.push(c.id);
      cardsBySet.set(code, arr);
      if (p.name && !nameBySet.has(code)) nameBySet.set(code, p.name);
    }
  }

  console.log("→ Fetching set list from YGOPRODeck…");
  const upstream: UpstreamSet[] = await fetchJson(YGO.cardsets);
  console.log(`  upstream returned ${upstream.length} sets`);
  const upByCode = new Map<string, UpstreamSet>();
  for (const s of upstream) if (!upByCode.has(s.set_code)) upByCode.set(s.set_code, s);

  // Build an entry for EVERY set that has cards in our DB — the union of
  // YGOPRODeck's list and the set codes present on cards. YGOPRODeck's cardsets
  // endpoint silently omits whole sets (e.g. Battles of Legend: Glorious
  // Gallery, 2-Player Starter Set, Dark Beginning); without this union those
  // sets would have no name/date and show "—" in the app.
  const sets = [...cardsBySet.entries()].map(([code, cards]) => {
    const up = upByCode.get(code);
    return {
      code,
      name: up?.set_name ?? nameBySet.get(code) ?? code,
      tcgDate: up?.tcg_date ?? null,
      numCards: up?.num_of_cards ?? cards.length,
      cards,
    };
  });
  console.log(`  ${sets.length} sets have cards in the local DB`);

  // Backfill release dates from Yugipedia for sets upstream omitted or left
  // undated. Cache by name so duplicate codes for one set query Yugipedia once.
  const needDate = sets.filter((s) => !s.tcgDate);
  if (needDate.length) {
    console.log(`→ Backfilling release dates from Yugipedia for ${needDate.length} set(s)…`);
    const dateByName = new Map<string, string | null>();
    for (const s of needDate) {
      if (!dateByName.has(s.name)) dateByName.set(s.name, await fetchSetReleaseDate(s.name));
      s.tcgDate = dateByName.get(s.name) ?? null;
    }
    const filled = needDate.filter((s) => s.tcgDate).length;
    console.log(`  recovered dates for ${filled}/${needDate.length} set(s)`);
  }

  sets.sort((a, b) => (a.tcgDate ?? "").localeCompare(b.tcgDate ?? ""));

  await writeJson(PATHS.setsDb, {
    _comment: "Generated by scripts/import-sets.ts from YGOPRODeck. TCG only. Do not hand-edit.",
    source: YGO.source,
    generatedAt: new Date().toISOString(),
    count: sets.length,
    sets,
  });

  await writeJson(join(PATHS.sets, "index.json"), {
    _comment: "Generated by scripts/import-sets.ts. TCG only. Do not hand-edit.",
    sets: sets.map((s) => ({ code: s.code, name: s.name, tcgDate: s.tcgDate, numCards: s.cards.length })),
  });

  console.log(`✓ Wrote ${sets.length} sets → assets/sets/db.json (+ index.json)`);
  console.log("  Next: `pnpm build:images` to download set logos.");
}

main().catch((err) => {
  console.error("✗ import-sets failed:", err);
  process.exit(1);
});
