import { join } from "node:path";
import { PATHS, YGO, fetchJson, fetchSetReleaseDate, writeJson, readJson, isoDate, hasFlag } from "./_lib.ts";

interface CardLite {
  id: number;
  sets: { code: string; name: string }[];
}
interface UpstreamSet {
  set_name: string;
  set_code: string;
  num_of_cards?: number;
  tcg_date?: string;
}

const prefixOf = (code: string): string => code.split("-")[0]!;

async function main() {
  const db = await readJson<{ cards: CardLite[] }>(PATHS.cardsDb);
  if (!db || !Array.isArray(db.cards)) {
    console.error("✗ engine/cards/db.json not found. Run `pnpm import:cards` first.");
    process.exit(1);
  }

  const cardsBySet = new Map<string, number[]>();
  const nameBySet = new Map<string, string>();
  for (const c of db.cards) {
    for (const p of c.sets ?? []) {
      const code = prefixOf(p.code);
      const arr = cardsBySet.get(code) ?? [];
      arr.push(c.id);
      cardsBySet.set(code, arr);
      if (p.name && !nameBySet.has(code)) nameBySet.set(code, p.name);
    }
  }

  console.log("→ Fetching set list from YGOPRODeck…");
  const upstream: UpstreamSet[] = await fetchJson(YGO.cardsets);
  console.log(`  upstream returned ${upstream.length} sets`);
  const upByCode = new Map<string, UpstreamSet>();
  for (const s of upstream) if (!upByCode.has(s.set_code)) upByCode.set(s.set_code, s);

  let sets = [...cardsBySet.entries()].map(([code, cards]) => {
    const up = upByCode.get(code);
    return {
      code,
      name: up?.set_name ?? nameBySet.get(code) ?? code,
      tcgDate: up?.tcg_date ?? null,
      numCards: up?.num_of_cards ?? cards.length,
      cards,
    };
  });
  console.log(`  ${sets.length} sets have cards in the local DB`);

  const needDate = sets.filter((s) => !s.tcgDate);
  if (needDate.length) {
    console.log(`→ Backfilling release dates from Yugipedia for ${needDate.length} set(s)…`);
    const dateByName = new Map<string, string | null>();
    for (const s of needDate) {
      if (!dateByName.has(s.name)) dateByName.set(s.name, await fetchSetReleaseDate(s.name));
      s.tcgDate = dateByName.get(s.name) ?? null;
    }
    const filled = needDate.filter((s) => s.tcgDate).length;
    console.log(`  recovered dates for ${filled}/${needDate.length} set(s)`);
  }

  const today = isoDate();
  const upcoming = sets.filter((s) => s.tcgDate && s.tcgDate > today);
  if (upcoming.length && !hasFlag("include-unreleased")) {
    sets = sets.filter((s) => !(s.tcgDate && s.tcgDate > today));
    console.log(
      `  dropped ${upcoming.length} unreleased set(s) (after ${today}): ${upcoming
        .map((s) => `${s.code} ${s.tcgDate}`)
        .join(", ")}`,
    );
  }

  sets.sort((a, b) => (a.tcgDate ?? "").localeCompare(b.tcgDate ?? ""));

  await writeJson(PATHS.setsDb, {
    _comment: "Generated by scripts/import-sets.ts from YGOPRODeck. TCG only. Do not hand-edit.",
    source: YGO.source,
    generatedAt: new Date().toISOString(),
    count: sets.length,
    sets,
  });

  await writeJson(PATHS.setsIndex, {
    _comment: "Generated by scripts/import-sets.ts. TCG only. Do not hand-edit.",
    sets: sets.map((s) => ({ code: s.code, name: s.name, tcgDate: s.tcgDate, numCards: s.cards.length })),
  });

  console.log(`✓ Wrote ${sets.length} sets → engine/sets/db.json (+ index.json)`);
  console.log("  Next: `pnpm build:images` to download set logos.");
}

main().catch((err) => {
  console.error("✗ import-sets failed:", err);
  process.exit(1);
});
