import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { PATHS, GENESYS_OFFICIAL, fetchText, readJson, writeJson, exists, ensureDir } from "./_lib.ts";

const EFFECTIVE_DATE = "2026-08-03";
const POINT_CAP = 100;
const SOURCE = `${GENESYS_OFFICIAL} (Konami official, effective ${EFFECTIVE_DATE})`;

interface GItem {
  id: number;
  name: string;
  points: number;
}
interface Revision {
  date: string;
  format: "TCG";
  pointCap: number | null;
  source: string;
  fetchedAt: string;
  cards: GItem[];
}

const norm = (s: string) =>
  s.toLowerCase()
    .replace(/[‘’ʼ`]/g, "'")
    .replace(/[“”"]/g, "")
    .replace(/[-–—]/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
    .trim();

const ALIASES: Record<string, string> = {
  "exstellarknight constellar ptolemy o7": "exstellarknight constellar ptolemy ω7",
  "calamity of the sacred beasts hamon, lord of striking thunder":
    "hamon, lord of striking thunder sacred beast of sinful catastrophe",
  "infinity of the sacred beasts raviel, lord of phantasms":
    "raviel, lord of phantasms sacred beast of endless eternity",
  "stellarnova binding": "stellarnova bonds",
  "the three champions of swordsoul": "the three brave swordsouls",
  "k9 �� lupis": "k9 øø lupis",
};

function decodeEntities(s: string): string {
  return s
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(parseInt(d, 10)))
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&nbsp;/g, " ")
    .replace(/&rsquo;|&lsquo;/g, "'")
    .replace(/&ldquo;|&rdquo;/g, '"')
    .replace(/&gt;/g, ">")
    .replace(/&lt;/g, "<");
}

function parseOfficialTable(html: string): Array<[string, number]> {
  const table = html.match(/<table[\s\S]*?<\/table>/i)?.[0];
  if (!table) return [];
  const out: Array<[string, number]> = [];
  for (const row of table.match(/<tr[\s\S]*?<\/tr>/gi) ?? []) {
    const cells = [...row.matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map((m) =>
      decodeEntities(m[1]!.replace(/<[^>]+>/g, "")).replace(/\s+/g, " ").trim(),
    );
    if (cells.length < 2) continue;
    const [name, pts] = [cells[0]!, cells[1]!];
    if (!/^\d+$/.test(pts)) continue;
    if (name) out.push([name, Number(pts)]);
  }
  return out;
}

async function regenerateIndex(): Promise<number> {
  await ensureDir(PATHS.genesys);
  const files = (await readdir(PATHS.genesys)).filter((f) => /^\d{4}-\d{2}-\d{2}\.json$/.test(f));
  files.sort().reverse();
  const revisions = [];
  for (const file of files) {
    const data = JSON.parse(await readFile(join(PATHS.genesys, file), "utf8")) as Revision;
    revisions.push({
      date: data.date,
      file,
      cardCount: data.cards?.length ?? 0,
      pointCap: data.pointCap ?? null,
    });
  }
  await writeJson(PATHS.genesysIndex, {
    _comment: "Generated by scripts/update-genesys.ts. TCG only. Do not hand-edit.",
    revisions,
  });
  return revisions.length;
}

async function main() {
  const db = await readJson<{ cards: Array<{ id: number; name: string }> }>(PATHS.cardsDb);
  if (!db?.cards?.length) {
    console.error("✗ engine/cards/db.json not found. Run `pnpm import:cards` first.");
    process.exit(1);
  }
  const idByName = new Map<string, number>();
  const nameById = new Map<number, string>();
  for (const c of db.cards) {
    idByName.set(norm(c.name), c.id);
    nameById.set(c.id, c.name);
  }

  console.log("→ Fetching the official Genesys points list…");
  const entries = parseOfficialTable(await fetchText(GENESYS_OFFICIAL));
  if (entries.length === 0) {
    console.error(`✗ no Genesys table found at ${GENESYS_OFFICIAL} — the page layout may have changed.`);
    process.exit(1);
  }
  const pts = entries.map(([, p]) => p);
  console.log(`  ${entries.length} carded entries (points ${Math.min(...pts)}–${Math.max(...pts)})`);

  const cards: GItem[] = [];
  const unresolved: string[] = [];
  for (const [rawName, points] of entries) {
    const key = norm(rawName);
    const id = idByName.get(ALIASES[key] ?? key);
    if (id == null) {
      unresolved.push(rawName);
      continue;
    }
    cards.push({ id, name: nameById.get(id)!, points });
  }
  cards.sort((a, b) => b.points - a.points || a.name.localeCompare(b.name));

  const file = join(PATHS.genesys, `${EFFECTIVE_DATE}.json`);
  if (await exists(file)) {
    console.log(`  ${EFFECTIVE_DATE}.json already archived — append-only, leaving it untouched.`);
  } else {
    const revision: Revision = {
      date: EFFECTIVE_DATE,
      format: "TCG",
      pointCap: POINT_CAP,
      source: SOURCE,
      fetchedAt: new Date().toISOString(),
      cards,
    };
    await writeJson(file, revision);
    console.log(`  wrote snapshot → engine/genesys/${EFFECTIVE_DATE}.json (${cards.length} cards, cap ${POINT_CAP})`);
  }

  if (unresolved.length) {
    console.log(`  ⚠ ${unresolved.length} entr(y/ies) not in the TCG db, skipped: ${unresolved.join(", ")}`);
    console.log("    (run `pnpm import:cards` first if a new set just dropped, then add an alias here)");
  }

  const total = await regenerateIndex();
  console.log(`✓ Done. ${total} Genesys revision(s) archived.`);
}

main().catch((err) => {
  console.error("✗ update-genesys failed:", err);
  process.exit(1);
});
