// scripts/update-genesys.ts
//
// BUILD-TIME ONLY. Run manually by Red.
//
//   pnpm import:genesys
//
// Archives the CURRENT Genesys points list as an immutable dated snapshot:
//
//   assets/genesys/YYYY-MM-DD.json
//
// Genesys is Konami's TCG points-based format: each listed card carries a
// point value (1–100) and a legal deck (Main+Extra+Side combined) must stay
// under the point cap (standard 100); cards not on the list cost 0 points.
//
// SOURCE LIMITATION (verified): there is no machine-readable archive of
// historical Genesys revisions. Konami's official blog posts publish point
// *changes* as images only (no tables/text), and the third-party JSON API used
// here (yugiohgenesysbuilder.com) serves only the CURRENT list. So each run
// snapshots whatever is current; older revisions cannot be back-filled the way
// the TCG banlists were. The file is dated by the latest known effective
// Genesys update so re-running on the same revision is a no-op (append-only).
//
// TCG ONLY. Network access is confined to importer scripts; the running app
// reads only the local files under assets/genesys/.

import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { PATHS, GENESYS_API, fetchJson, readJson, writeJson, exists, ensureDir, sleep } from "./_lib.ts";

// Effective date of the current list (latest published Genesys update). Bump
// this when Konami publishes a new list so a new dated snapshot is written.
const EFFECTIVE_DATE = "2026-04-30";
// Genesys deck point cap (Konami's standard). Adjust if a revision changes it.
const POINT_CAP = 100;
const SOURCE = "yugiohgenesysbuilder.com/api/cards";

interface GItem {
  id: number;
  name: string;
  points: number;
}
interface Revision {
  date: string;
  pointCap: number | null;
  source: string;
  fetchedAt: string;
  cards: GItem[];
}

async function fetchAll(): Promise<GItem[]> {
  const out: GItem[] = [];
  let offset = 0;
  for (let guard = 0; guard < 100; guard++) {
    const page = await fetchJson(`${GENESYS_API}?offset=${offset}&limit=100`);
    if (!page) break;
    for (const c of page.items ?? []) {
      if (typeof c?.id === "number" && typeof c?.points === "number") {
        out.push({ id: c.id, name: c.name ?? "", points: c.points });
      }
    }
    if (!page.hasMore) break;
    offset = page.nextOffset;
    await sleep(150);
  }
  return out;
}

async function regenerateIndex(): Promise<number> {
  await ensureDir(PATHS.genesys);
  const files = (await readdir(PATHS.genesys)).filter((f) => /^\d{4}-\d{2}-\d{2}\.json$/.test(f));
  files.sort().reverse();
  const revisions = [];
  for (const file of files) {
    const data = JSON.parse(await readFile(join(PATHS.genesys, file), "utf8")) as Revision;
    revisions.push({ date: data.date, file, cardCount: data.cards?.length ?? 0 });
  }
  await writeJson(PATHS.genesysIndex, {
    _comment: "Generated by scripts/update-genesys.ts. TCG only. Do not hand-edit.",
    revisions,
  });
  return revisions.length;
}

async function main() {
  console.log("→ Fetching current Genesys points list…");
  const items = await fetchAll();
  if (items.length === 0) {
    console.error("✗ no Genesys data returned from upstream.");
    process.exit(1);
  }
  const pts = items.map((c) => c.points);
  console.log(`  ${items.length} carded entries (points ${Math.min(...pts)}–${Math.max(...pts)})`);

  // Prefer card names from our local DB for consistency; fall back to API name.
  const db = await readJson<{ cards: Array<{ id: number; name: string }> }>(PATHS.cardsDb);
  const nameOf = new Map<number, string>();
  if (db?.cards) for (const c of db.cards) nameOf.set(c.id, c.name);

  const cards = items
    .map((c) => ({ id: c.id, name: nameOf.get(c.id) ?? c.name, points: c.points }))
    .sort((a, b) => b.points - a.points || a.name.localeCompare(b.name));

  const file = join(PATHS.genesys, `${EFFECTIVE_DATE}.json`);
  if (await exists(file)) {
    console.log(`  ${EFFECTIVE_DATE}.json already archived — append-only, leaving it untouched.`);
  } else {
    const revision: Revision = {
      date: EFFECTIVE_DATE,
      pointCap: POINT_CAP,
      source: SOURCE,
      fetchedAt: new Date().toISOString(),
      cards,
    };
    await writeJson(file, revision);
    console.log(`  wrote snapshot → assets/genesys/${EFFECTIVE_DATE}.json (cap ${POINT_CAP})`);
  }

  const total = await regenerateIndex();
  console.log(`✓ Done. ${total} Genesys revision(s) archived.`);
  console.log("  Note: only the current list is available upstream — historical revisions are not machine-readable.");
}

main().catch((err) => {
  console.error("✗ update-genesys failed:", err);
  process.exit(1);
});
