// scripts/update-banlists.ts
//
// BUILD-TIME ONLY. Run manually by Red.
//
//   pnpm import:banlists
//
// Archives EVERY historical TCG banlist revision as immutable per-revision
// JSON snapshots:
//
//   assets/banlists/YYYY-MM-DD.json
//
// SOURCE: the comprehensive YGOPro forbidden/limited list
// (Fluorohydride/ygopro lflist.conf), which accumulates every past list in a
// single file. Each list is a section headed by `!YYYY.M[.D] TCG`; bare
// `!YYYY.M` headers are OCG and are skipped (TCG ONLY). Body lines are
// `passcode limit --name`, where 0=Forbidden, 1=Limited, 2=Semi-Limited.
// Card names are resolved from assets/cards/db.json by passcode.
//
// Behavior:
//   - Append-only. Existing dated files are never overwritten.
//   - Regenerate assets/banlists/index.json as a sorted manifest.
//
// Only the importer scripts may touch the network. The running app reads only
// the local files under assets/banlists/ and never fetches at runtime.

import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import {
  PATHS,
  LFLIST_URL,
  fetchText,
  writeJson,
  readJson,
  exists,
  ensureDir,
} from "./_lib.ts";

interface Entry {
  id: number;
  name: string;
}
interface Revision {
  date: string;
  format: "TCG";
  source: string;
  fetchedAt: string;
  forbidden: Entry[];
  limited: Entry[];
  semiLimited: Entry[];
}

interface ParsedList {
  date: string; // YYYY-MM-DD
  forbidden: number[];
  limited: number[];
  semiLimited: number[];
}

/** `!2026.5 TCG` / `!2014.1.1 TCG` → "2026-05-01" / "2014-01-01". OCG → null. */
function headerToDate(header: string): string | null {
  const m = header.match(/^!\s*(\d{4})\.(\d{1,2})(?:\.(\d{1,2}))?\s+TCG\b/i);
  if (!m) return null;
  const [, y, mo, d] = m;
  const pad = (s: string) => s.padStart(2, "0");
  return `${y}-${pad(mo!)}-${pad(d ?? "1")}`;
}

/** Parse the comprehensive lflist into per-revision TCG lists. */
function parseLflist(text: string): ParsedList[] {
  const lists: ParsedList[] = [];
  let cur: ParsedList | null = null;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (line.startsWith("!")) {
      const date = headerToDate(line);
      cur = date ? { date, forbidden: [], limited: [], semiLimited: [] } : null;
      if (cur) lists.push(cur);
      continue;
    }
    if (!cur || !line || line.startsWith("#")) continue;
    const m = line.match(/^(\d+)\s+(-?\d+)/);
    if (!m) continue;
    const id = parseInt(m[1]!, 10);
    const limit = parseInt(m[2]!, 10);
    if (limit === 0) cur.forbidden.push(id);
    else if (limit === 1) cur.limited.push(id);
    else if (limit === 2) cur.semiLimited.push(id);
    // limit >= 3 (unlimited) shouldn't appear, but is ignored if it does.
  }
  return lists;
}

async function regenerateIndex(): Promise<number> {
  await ensureDir(PATHS.banlists);
  const files = (await readdir(PATHS.banlists)).filter((f) => /^\d{4}-\d{2}-\d{2}\.json$/.test(f));
  files.sort().reverse(); // newest first
  const revisions = [];
  for (const file of files) {
    const data = JSON.parse(await readFile(join(PATHS.banlists, file), "utf8")) as Revision;
    revisions.push({
      date: data.date,
      file,
      forbidden: data.forbidden?.length ?? 0,
      limited: data.limited?.length ?? 0,
      semiLimited: data.semiLimited?.length ?? 0,
    });
  }
  await writeJson(PATHS.banlistIndex, {
    _comment: "Generated by scripts/update-banlists.ts. TCG only. Do not hand-edit.",
    revisions,
  });
  return revisions.length;
}

async function main() {
  // Card-name lookup from the local DB (so revision files are human-readable).
  const db = await readJson<{ cards: Entry[] }>(PATHS.cardsDb);
  const nameOf = new Map<number, string>();
  if (db?.cards) for (const c of db.cards) nameOf.set(c.id, c.name);
  if (nameOf.size === 0) {
    console.warn("⚠ cards/db.json not found — names will be blank. Run `pnpm import:cards` first for readable lists.");
  }

  console.log("→ Fetching comprehensive forbidden/limited list…");
  const text = await fetchText(LFLIST_URL);
  const lists = parseLflist(text);
  console.log(`  parsed ${lists.length} historical TCG list(s)`);

  const toEntries = (ids: number[]): Entry[] =>
    ids
      .map((id) => ({ id, name: nameOf.get(id) ?? "" }))
      .sort((a, b) => a.name.localeCompare(b.name));

  let written = 0;
  let skipped = 0;
  for (const list of lists) {
    const file = join(PATHS.banlists, `${list.date}.json`);
    if (await exists(file)) {
      skipped++;
      continue; // append-only
    }
    const revision: Revision = {
      date: list.date,
      format: "TCG",
      source: `${LFLIST_URL} (Fluorohydride/ygopro)`,
      fetchedAt: new Date().toISOString(),
      forbidden: toEntries(list.forbidden),
      limited: toEntries(list.limited),
      semiLimited: toEntries(list.semiLimited),
    };
    await writeJson(file, revision);
    written++;
  }

  const total = await regenerateIndex();
  console.log(`✓ Done. Wrote ${written} new, skipped ${skipped} existing. ${total} revision(s) archived.`);
}

main().catch((err) => {
  console.error("✗ update-banlists failed:", err);
  process.exit(1);
});
